#!/bin/sh /etc/rc.common
USE_PROCD=1

START=90
STOP=10

enabled="$(uci get komari-agent.config.enabled)"
tls="$(uci get komari-agent.config.tls)"
host="$(uci get komari-agent.config.host)"
secret="$(uci get komari-agent.config.secret)"

start_service() {
        [ "$enabled" == "1" ] || return
        procd_open_instance
        if [ "$tls" == "1" ]
        then
                procd_set_param command /usr/bin/komari-agent -e "${host}" -t "${secret}" --disable-auto-update --tls
        else
                procd_set_param command /usr/bin/komari-agent -e "${host}" -t "${secret}" --disable-auto-update
        fi
        procd_set_param respawn
        [ -e /proc/sys/kernel/core_pattern ] && {
                procd_set_param limits core="unlimited"
        }
        procd_close_instance
}

service_triggers() {
        procd_add_reload_trigger "komari-agent"
}

reload_service() {
  stop
  start
}
